### ISSUE TITLE
Mapbox and mapkit examples seem to be broken on the demo site.

### ISSUE THREAD

**Issue by ohbadiah** [roblabs/maps-withastro#2]
404 on https://roblabs.com/xyz-raster-sources/styles/naturalearthtiles.json seems to be the cause.

**Comment by roblabs** [comment]
Thank you, Fixed! 

The server below had issues with its Secure cert. 

* https://RobLabs.com/xyz - a collection of XYZ raster sources for MapLibre, Mapbox, QGIS, mobile, Astro
